# Vector Arithmetic

In [2]:
import numpy as np

In [5]:
vec = np.array([3,5,7,9])
print(vec)
print(len(vec))

[3 5 7 9]
4


## Vector Addition

$c=a+b$

In [9]:
# define first vector
a = np.array([91, 23, 13])
print(a)

# define second vector
b = np.array([18, 42, 31])
print(b)

# add vectors
c = a + b
print(c)

[91 23 13]
[18 42 31]
[109  65  44]


## Vector Subtraction

$c=a-b$

In [13]:
# define first vector
a = np.array([33, 108, 9])
print(a)

# define second vector
b = np.array([92, 34, 87])
print(b)

# add vectors
c = a - b
print(c)

[ 33 108   9]
[92.  34.  87.3]
[-59.   74.  -78.3]


## Vector Multiplication

$c = a * b$

In [14]:
# define first vector
a = np.array([33, 14.2, 9])
print(a)

# define second vector
b = np.array([3.9, 34, 105])
print(b)

# add vectors
c = a * b
print(c)

[33.  14.2  9. ]
[  3.9  34.  105. ]
[128.7 482.8 945. ]


## Vector Division

$c=\frac{a}{b}$

In [15]:
# define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)

# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


## Vector Dot Product

$c = a · b$

In [17]:
# define first vector
a = np.array([1, 2, 3])
print(a)

# define second vector
b = np.array([1, 2, 3])
print(b)

# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


## Vector Scalar Multiplication

$c=sa$

In [20]:
# define vector
a = np.array([1, 2, 3])
print(a)

# define scalar
s = 0.5
print(s)

# multiplication
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]
